### ISSUE TITLE
Avatar?

### ISSUE THREAD

**Issue by wluijk** [microsoftgraph/msgraph-training-angularspa#7]
Browser gives in console a TypeError: Cannot read property 'avatar' of undefined
It seems avatar is no longer a property of /me
Do we need to work it around to /me/photo?

**Comment by jasonjoh** [comment]
I actually put in the plumbing for the avatar, but this tutorial doesn't cover getting it from Graph (that's something we're planning on adding later in additional tutorials that build on this simple app). So for now it's by design that you get the default avatar always.

What you'd need to do is update the `getUser` method in auth.service.ts to make an additional call to `/me/photo/$value` like:

```
let userPhotoStream = await graphClient.api('/me/photo/$value').getStream(null);
```

This returns a `ReadableStream`. You'd need to read all the data out of it, convert it to a base64 string and generate a Data URI, then save that in the `user.avatar`.
